FROM golang:1.24-alpine AS builder

# 设置工作目录
WORKDIR /build

# 复制go.mod和go.sum文件
COPY go.mod go.sum ./

# 下载依赖
RUN go env -w  GOPROXY=https://goproxy.cn,direct && go mod download

# 复制整个项目
COPY . .

# 构建应用程序
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/user_api ./apps/user/api

# 使用alpine作为最终镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 从builder阶段复制构建好的二进制文件
COPY --from=builder /build/user_api /app/user_api

# 复制配置文件
COPY apps/user/api/etc /app/etc

# 安装必要的系统依赖
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk --no-cache add ca-certificates && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 暴露端口
EXPOSE 8888

# 设置启动命令
CMD ["/app/user_api", "-f", "/app/etc/user.yaml"]