// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: apps/social/rpc/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	AddSource     int32                  `protobuf:"varint,4,opt,name=addSource,proto3" json:"addSource,omitempty"` // 添加来源
	FriendUid     string                 `protobuf:"bytes,5,opt,name=friendUid,proto3" json:"friendUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{0}
}

func (x *Friend) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *Friend) GetFriendUid() string {
	if x != nil {
		return x.FriendUid
	}
	return ""
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ReqUid        string                 `protobuf:"bytes,3,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	HandleResult  int32                  `protobuf:"varint,6,opt,name=handleResult,proto3" json:"handleResult,omitempty"` // 处理结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendRequest) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *FriendRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *FriendRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type Group struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon            string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Status          int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatorUid      string                 `protobuf:"bytes,5,opt,name=creator_uid,json=creatorUid,proto3" json:"creator_uid,omitempty"`
	GroupType       int32                  `protobuf:"varint,6,opt,name=groupType,proto3" json:"groupType,omitempty"`
	IsVerify        bool                   `protobuf:"varint,7,opt,name=isVerify,proto3" json:"isVerify,omitempty"`
	Notification    string                 `protobuf:"bytes,8,opt,name=notification,proto3" json:"notification,omitempty"` // 公告通知
	NotificationUid string                 `protobuf:"bytes,9,opt,name=notificationUid,proto3" json:"notificationUid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Group) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Group) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

func (x *Group) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *Group) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

func (x *Group) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *Group) GetNotificationUid() string {
	if x != nil {
		return x.NotificationUid
	}
	return ""
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	RoleLevel     int32                  `protobuf:"varint,4,opt,name=roleLevel,proto3" json:"roleLevel,omitempty"`
	JoinTime      int64                  `protobuf:"varint,5,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,6,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,7,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,8,opt,name=operatorUid,proto3" json:"operatorUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{3}
}

func (x *GroupMember) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMember) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *GroupMember) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *GroupMember) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupMember) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *GroupMember) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ReqId         string                 `protobuf:"bytes,3,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,6,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,7,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	HandleUid     string                 `protobuf:"bytes,8,opt,name=handleUid,proto3" json:"handleUid,omitempty"`
	HandleResult  int32                  `protobuf:"varint,9,opt,name=handleResult,proto3" json:"handleResult,omitempty"` // 处理结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GroupRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupRequest) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupRequest) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *GroupRequest) GetHandleUid() string {
	if x != nil {
		return x.HandleUid
	}
	return ""
}

func (x *GroupRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type FriendPutInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReqUid        string                 `protobuf:"bytes,2,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInReq) Reset() {
	*x = FriendPutInReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInReq) ProtoMessage() {}

func (x *FriendPutInReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInReq.ProtoReflect.Descriptor instead.
func (*FriendPutInReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{5}
}

func (x *FriendPutInReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendPutInReq) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *FriendPutInReq) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendPutInReq) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

type FriendPutInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInResp) Reset() {
	*x = FriendPutInResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInResp) ProtoMessage() {}

func (x *FriendPutInResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInResp.ProtoReflect.Descriptor instead.
func (*FriendPutInResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{6}
}

type FriendPutInHandleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendReqId   int32                  `protobuf:"varint,1,opt,name=friendReqId,proto3" json:"friendReqId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	HandleResult  int32                  `protobuf:"varint,3,opt,name=handleResult,proto3" json:"handleResult,omitempty"` // 处理结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInHandleReq) Reset() {
	*x = FriendPutInHandleReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInHandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInHandleReq) ProtoMessage() {}

func (x *FriendPutInHandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInHandleReq.ProtoReflect.Descriptor instead.
func (*FriendPutInHandleReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{7}
}

func (x *FriendPutInHandleReq) GetFriendReqId() int32 {
	if x != nil {
		return x.FriendReqId
	}
	return 0
}

func (x *FriendPutInHandleReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendPutInHandleReq) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type FriendPutInHandleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInHandleResp) Reset() {
	*x = FriendPutInHandleResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInHandleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInHandleResp) ProtoMessage() {}

func (x *FriendPutInHandleResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInHandleResp.ProtoReflect.Descriptor instead.
func (*FriendPutInHandleResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{8}
}

type FriendPutInListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInListReq) Reset() {
	*x = FriendPutInListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInListReq) ProtoMessage() {}

func (x *FriendPutInListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInListReq.ProtoReflect.Descriptor instead.
func (*FriendPutInListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{9}
}

func (x *FriendPutInListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendPutInListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FriendRequest       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInListResp) Reset() {
	*x = FriendPutInListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInListResp) ProtoMessage() {}

func (x *FriendPutInListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInListResp.ProtoReflect.Descriptor instead.
func (*FriendPutInListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{10}
}

func (x *FriendPutInListResp) GetList() []*FriendRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type FriendListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListReq) Reset() {
	*x = FriendListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReq) ProtoMessage() {}

func (x *FriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReq.ProtoReflect.Descriptor instead.
func (*FriendListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{11}
}

func (x *FriendListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Friend              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListResp) Reset() {
	*x = FriendListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResp) ProtoMessage() {}

func (x *FriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResp.ProtoReflect.Descriptor instead.
func (*FriendListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{12}
}

func (x *FriendListResp) GetList() []*Friend {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatorUid    string                 `protobuf:"bytes,4,opt,name=creator_uid,json=creatorUid,proto3" json:"creator_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateReq) Reset() {
	*x = GroupCreateReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateReq) ProtoMessage() {}

func (x *GroupCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateReq.ProtoReflect.Descriptor instead.
func (*GroupCreateReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{13}
}

func (x *GroupCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupCreateReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GroupCreateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupCreateReq) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

type GroupCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateResp) Reset() {
	*x = GroupCreateResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResp) ProtoMessage() {}

func (x *GroupCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateResp.ProtoReflect.Descriptor instead.
func (*GroupCreateResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{14}
}

func (x *GroupCreateResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupPutInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ReqId         string                 `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,5,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,6,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInReq) Reset() {
	*x = GroupPutInReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInReq) ProtoMessage() {}

func (x *GroupPutInReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInReq.ProtoReflect.Descriptor instead.
func (*GroupPutInReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{15}
}

func (x *GroupPutInReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPutInReq) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GroupPutInReq) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupPutInReq) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupPutInReq) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupPutInReq) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

type GroupPutInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInResp) Reset() {
	*x = GroupPutInResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInResp) ProtoMessage() {}

func (x *GroupPutInResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInResp.ProtoReflect.Descriptor instead.
func (*GroupPutInResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{16}
}

type GroupPutInListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInListReq) Reset() {
	*x = GroupPutInListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInListReq) ProtoMessage() {}

func (x *GroupPutInListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInListReq.ProtoReflect.Descriptor instead.
func (*GroupPutInListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{17}
}

func (x *GroupPutInListReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupPutInListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupRequest        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInListResp) Reset() {
	*x = GroupPutInListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInListResp) ProtoMessage() {}

func (x *GroupPutInListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInListResp.ProtoReflect.Descriptor instead.
func (*GroupPutInListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{18}
}

func (x *GroupPutInListResp) GetList() []*GroupRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupPutInHandleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupReqId    int32                  `protobuf:"varint,1,opt,name=groupReqId,proto3" json:"groupReqId,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	HandleUid     string                 `protobuf:"bytes,3,opt,name=handleUid,proto3" json:"handleUid,omitempty"`
	HandleResult  int32                  `protobuf:"varint,4,opt,name=handleResult,proto3" json:"handleResult,omitempty"` // 处理结果
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	UserAvatarUrl string                 `protobuf:"bytes,6,opt,name=userAvatarUrl,proto3" json:"userAvatarUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInHandleReq) Reset() {
	*x = GroupPutInHandleReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInHandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInHandleReq) ProtoMessage() {}

func (x *GroupPutInHandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInHandleReq.ProtoReflect.Descriptor instead.
func (*GroupPutInHandleReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{19}
}

func (x *GroupPutInHandleReq) GetGroupReqId() int32 {
	if x != nil {
		return x.GroupReqId
	}
	return 0
}

func (x *GroupPutInHandleReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPutInHandleReq) GetHandleUid() string {
	if x != nil {
		return x.HandleUid
	}
	return ""
}

func (x *GroupPutInHandleReq) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

func (x *GroupPutInHandleReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupPutInHandleReq) GetUserAvatarUrl() string {
	if x != nil {
		return x.UserAvatarUrl
	}
	return ""
}

type GroupPutInHandleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInHandleResp) Reset() {
	*x = GroupPutInHandleResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInHandleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInHandleResp) ProtoMessage() {}

func (x *GroupPutInHandleResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInHandleResp.ProtoReflect.Descriptor instead.
func (*GroupPutInHandleResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{20}
}

func (x *GroupPutInHandleResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListReq) Reset() {
	*x = GroupListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListReq) ProtoMessage() {}

func (x *GroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListReq.ProtoReflect.Descriptor instead.
func (*GroupListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{21}
}

func (x *GroupListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GroupListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Group               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResp) Reset() {
	*x = GroupListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResp) ProtoMessage() {}

func (x *GroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResp.ProtoReflect.Descriptor instead.
func (*GroupListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{22}
}

func (x *GroupListResp) GetList() []*Group {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUsersReq) Reset() {
	*x = GroupUsersReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUsersReq) ProtoMessage() {}

func (x *GroupUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUsersReq.ProtoReflect.Descriptor instead.
func (*GroupUsersReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{23}
}

func (x *GroupUsersReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupMember         `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUsersResp) Reset() {
	*x = GroupUsersResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUsersResp) ProtoMessage() {}

func (x *GroupUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUsersResp.ProtoReflect.Descriptor instead.
func (*GroupUsersResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{24}
}

func (x *GroupUsersResp) GetList() []*GroupMember {
	if x != nil {
		return x.List
	}
	return nil
}

var File_apps_social_rpc_social_proto protoreflect.FileDescriptor

const file_apps_social_rpc_social_proto_rawDesc = "" +
	"\n" +
	"\x1capps/social/rpc/social.proto\x12\x06social\"\x84\x01\n" +
	"\x06Friend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1c\n" +
	"\taddSource\x18\x04 \x01(\x05R\taddSource\x12\x1c\n" +
	"\tfriendUid\x18\x05 \x01(\tR\tfriendUid\"\xa5\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reqUid\x18\x03 \x01(\tR\x06reqUid\x12\x16\n" +
	"\x06reqMsg\x18\x04 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x05 \x01(\x03R\areqTime\x12\"\n" +
	"\fhandleResult\x18\x06 \x01(\x05R\fhandleResult\"\x80\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreator_uid\x18\x05 \x01(\tR\n" +
	"creatorUid\x12\x1c\n" +
	"\tgroupType\x18\x06 \x01(\x05R\tgroupType\x12\x1a\n" +
	"\bisVerify\x18\a \x01(\bR\bisVerify\x12\"\n" +
	"\fnotification\x18\b \x01(\tR\fnotification\x12(\n" +
	"\x0fnotificationUid\x18\t \x01(\tR\x0fnotificationUid\"\xeb\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x1c\n" +
	"\troleLevel\x18\x04 \x01(\x05R\troleLevel\x12\x1a\n" +
	"\bjoinTime\x18\x05 \x01(\x03R\bjoinTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\x06 \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\a \x01(\tR\n" +
	"inviterUid\x12 \n" +
	"\voperatorUid\x18\b \x01(\tR\voperatorUid\"\x82\x02\n" +
	"\fGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x14\n" +
	"\x05reqId\x18\x03 \x01(\tR\x05reqId\x12\x16\n" +
	"\x06reqMsg\x18\x04 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x05 \x01(\x03R\areqTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\x06 \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\a \x01(\tR\n" +
	"inviterUid\x12\x1c\n" +
	"\thandleUid\x18\b \x01(\tR\thandleUid\x12\"\n" +
	"\fhandleResult\x18\t \x01(\x05R\fhandleResult\"r\n" +
	"\x0eFriendPutInReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reqUid\x18\x02 \x01(\tR\x06reqUid\x12\x16\n" +
	"\x06reqMsg\x18\x03 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x04 \x01(\x03R\areqTime\"\x11\n" +
	"\x0fFriendPutInResp\"t\n" +
	"\x14FriendPutInHandleReq\x12 \n" +
	"\vfriendReqId\x18\x01 \x01(\x05R\vfriendReqId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\fhandleResult\x18\x03 \x01(\x05R\fhandleResult\"\x17\n" +
	"\x15FriendPutInHandleResp\",\n" +
	"\x12FriendPutInListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x13FriendPutInListResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.social.FriendRequestR\x04list\"'\n" +
	"\rFriendListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x0eFriendListResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.social.FriendR\x04list\"q\n" +
	"\x0eGroupCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreator_uid\x18\x04 \x01(\tR\n" +
	"creatorUid\"+\n" +
	"\x0fGroupCreateResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"\xb1\x01\n" +
	"\rGroupPutInReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05reqId\x18\x02 \x01(\tR\x05reqId\x12\x16\n" +
	"\x06reqMsg\x18\x03 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x04 \x01(\x03R\areqTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\x05 \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\x06 \x01(\tR\n" +
	"inviterUid\"\x10\n" +
	"\x0eGroupPutInResp\"-\n" +
	"\x11GroupPutInListReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\">\n" +
	"\x12GroupPutInListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.social.GroupRequestR\x04list\"\xd3\x01\n" +
	"\x13GroupPutInHandleReq\x12\x1e\n" +
	"\n" +
	"groupReqId\x18\x01 \x01(\x05R\n" +
	"groupReqId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x1c\n" +
	"\thandleUid\x18\x03 \x01(\tR\thandleUid\x12\"\n" +
	"\fhandleResult\x18\x04 \x01(\x05R\fhandleResult\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12$\n" +
	"\ruserAvatarUrl\x18\x06 \x01(\tR\ruserAvatarUrl\"0\n" +
	"\x14GroupPutInHandleResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"&\n" +
	"\fGroupListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\rGroupListResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.social.GroupR\x04list\")\n" +
	"\rGroupUsersReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"9\n" +
	"\x0eGroupUsersResp\x12'\n" +
	"\x04List\x18\x01 \x03(\v2\x13.social.GroupMemberR\x04List2\xaf\x05\n" +
	"\x06social\x12>\n" +
	"\vFriendPutIn\x12\x16.social.FriendPutInReq\x1a\x17.social.FriendPutInResp\x12P\n" +
	"\x11FriendPutInHandle\x12\x1c.social.FriendPutInHandleReq\x1a\x1d.social.FriendPutInHandleResp\x12J\n" +
	"\x0fFriendPutInList\x12\x1a.social.FriendPutInListReq\x1a\x1b.social.FriendPutInListResp\x12;\n" +
	"\n" +
	"FriendList\x12\x15.social.FriendListReq\x1a\x16.social.FriendListResp\x12>\n" +
	"\vGroupCreate\x12\x16.social.GroupCreateReq\x1a\x17.social.GroupCreateResp\x12;\n" +
	"\n" +
	"GroupPutIn\x12\x15.social.GroupPutInReq\x1a\x16.social.GroupPutInResp\x12G\n" +
	"\x0eGroupPutInList\x12\x19.social.GroupPutInListReq\x1a\x1a.social.GroupPutInListResp\x12M\n" +
	"\x10GroupPutInHandle\x12\x1b.social.GroupPutInHandleReq\x1a\x1c.social.GroupPutInHandleResp\x128\n" +
	"\tGroupList\x12\x14.social.GroupListReq\x1a\x15.social.GroupListResp\x12;\n" +
	"\n" +
	"GroupUsers\x12\x15.social.GroupUsersReq\x1a\x16.social.GroupUsersRespB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_apps_social_rpc_social_proto_rawDescOnce sync.Once
	file_apps_social_rpc_social_proto_rawDescData []byte
)

func file_apps_social_rpc_social_proto_rawDescGZIP() []byte {
	file_apps_social_rpc_social_proto_rawDescOnce.Do(func() {
		file_apps_social_rpc_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)))
	})
	return file_apps_social_rpc_social_proto_rawDescData
}

var file_apps_social_rpc_social_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_apps_social_rpc_social_proto_goTypes = []any{
	(*Friend)(nil),                // 0: social.Friend
	(*FriendRequest)(nil),         // 1: social.FriendRequest
	(*Group)(nil),                 // 2: social.Group
	(*GroupMember)(nil),           // 3: social.GroupMember
	(*GroupRequest)(nil),          // 4: social.GroupRequest
	(*FriendPutInReq)(nil),        // 5: social.FriendPutInReq
	(*FriendPutInResp)(nil),       // 6: social.FriendPutInResp
	(*FriendPutInHandleReq)(nil),  // 7: social.FriendPutInHandleReq
	(*FriendPutInHandleResp)(nil), // 8: social.FriendPutInHandleResp
	(*FriendPutInListReq)(nil),    // 9: social.FriendPutInListReq
	(*FriendPutInListResp)(nil),   // 10: social.FriendPutInListResp
	(*FriendListReq)(nil),         // 11: social.FriendListReq
	(*FriendListResp)(nil),        // 12: social.FriendListResp
	(*GroupCreateReq)(nil),        // 13: social.GroupCreateReq
	(*GroupCreateResp)(nil),       // 14: social.GroupCreateResp
	(*GroupPutInReq)(nil),         // 15: social.GroupPutInReq
	(*GroupPutInResp)(nil),        // 16: social.GroupPutInResp
	(*GroupPutInListReq)(nil),     // 17: social.GroupPutInListReq
	(*GroupPutInListResp)(nil),    // 18: social.GroupPutInListResp
	(*GroupPutInHandleReq)(nil),   // 19: social.GroupPutInHandleReq
	(*GroupPutInHandleResp)(nil),  // 20: social.GroupPutInHandleResp
	(*GroupListReq)(nil),          // 21: social.GroupListReq
	(*GroupListResp)(nil),         // 22: social.GroupListResp
	(*GroupUsersReq)(nil),         // 23: social.GroupUsersReq
	(*GroupUsersResp)(nil),        // 24: social.GroupUsersResp
}
var file_apps_social_rpc_social_proto_depIdxs = []int32{
	1,  // 0: social.FriendPutInListResp.list:type_name -> social.FriendRequest
	0,  // 1: social.FriendListResp.list:type_name -> social.Friend
	4,  // 2: social.GroupPutInListResp.list:type_name -> social.GroupRequest
	2,  // 3: social.GroupListResp.list:type_name -> social.Group
	3,  // 4: social.GroupUsersResp.List:type_name -> social.GroupMember
	5,  // 5: social.social.FriendPutIn:input_type -> social.FriendPutInReq
	7,  // 6: social.social.FriendPutInHandle:input_type -> social.FriendPutInHandleReq
	9,  // 7: social.social.FriendPutInList:input_type -> social.FriendPutInListReq
	11, // 8: social.social.FriendList:input_type -> social.FriendListReq
	13, // 9: social.social.GroupCreate:input_type -> social.GroupCreateReq
	15, // 10: social.social.GroupPutIn:input_type -> social.GroupPutInReq
	17, // 11: social.social.GroupPutInList:input_type -> social.GroupPutInListReq
	19, // 12: social.social.GroupPutInHandle:input_type -> social.GroupPutInHandleReq
	21, // 13: social.social.GroupList:input_type -> social.GroupListReq
	23, // 14: social.social.GroupUsers:input_type -> social.GroupUsersReq
	6,  // 15: social.social.FriendPutIn:output_type -> social.FriendPutInResp
	8,  // 16: social.social.FriendPutInHandle:output_type -> social.FriendPutInHandleResp
	10, // 17: social.social.FriendPutInList:output_type -> social.FriendPutInListResp
	12, // 18: social.social.FriendList:output_type -> social.FriendListResp
	14, // 19: social.social.GroupCreate:output_type -> social.GroupCreateResp
	16, // 20: social.social.GroupPutIn:output_type -> social.GroupPutInResp
	18, // 21: social.social.GroupPutInList:output_type -> social.GroupPutInListResp
	20, // 22: social.social.GroupPutInHandle:output_type -> social.GroupPutInHandleResp
	22, // 23: social.social.GroupList:output_type -> social.GroupListResp
	24, // 24: social.social.GroupUsers:output_type -> social.GroupUsersResp
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_apps_social_rpc_social_proto_init() }
func file_apps_social_rpc_social_proto_init() {
	if File_apps_social_rpc_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_social_rpc_social_proto_goTypes,
		DependencyIndexes: file_apps_social_rpc_social_proto_depIdxs,
		MessageInfos:      file_apps_social_rpc_social_proto_msgTypes,
	}.Build()
	File_apps_social_rpc_social_proto = out.File
	file_apps_social_rpc_social_proto_goTypes = nil
	file_apps_social_rpc_social_proto_depIdxs = nil
}
