name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: '版本标签(不填则使用latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: registry.cn-shenzhen.aliyuncs.com
  NAMESPACE: zeroim

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true

    # 设置 QEMU 以支持多架构构建
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    # 修改Dockerfile不使用代理
    - name: Modify Dockerfile
      run: |
        sed -i 's/https:\/\/goproxy.cn,direct/direct/g' ./deploy/dockerfile/Dockerfile_user_api_dev
        sed -i 's/https:\/\/goproxy.cn,direct/direct/g' ./deploy/dockerfile/Dockerfile_user_rpc_dev
        sed -i 's/https:\/\/goproxy.cn,direct/direct/g' ./deploy/dockerfile/Dockerfile_social_rpc_dev
        sed -i 's/https:\/\/goproxy.cn,direct/direct/g' ./deploy/dockerfile/Dockerfile_social_api_dev

    # 使用 buildx 构建并推送多架构镜像
    - name: Build user-api and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/dockerfile/Dockerfile_user_api_dev
        push: true
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-user-api:${{ github.event.inputs.version_tag || 'latest' }}
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-user-api:${{ github.sha }}

    - name: Build user-rpc and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/dockerfile/Dockerfile_user_rpc_dev
        push: true
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-user-rpc:${{ github.event.inputs.version_tag || 'latest' }}
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-user-rpc:${{ github.sha }}

    - name: Build social-rpc and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/dockerfile/Dockerfile_social_rpc_dev
        push: true
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-social-rpc:${{ github.event.inputs.version_tag || 'latest' }}
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-social-rpc:${{ github.sha }}

    - name: Build social-api and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/dockerfile/Dockerfile_social_api_dev
        push: true
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-social-api:${{ github.event.inputs.version_tag || 'latest' }}
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/test-social-api:${{ github.sha }}
